apiVersion: v1
kind: ConfigMap
metadata:
  name: pronunt-aggregator-service-config
  namespace: prism
data:
  APP_NAME: pronunt-aggregator-service
  APP_ENV: production
  APP_HOST: 0.0.0.0
  APP_PORT: "8000"
  LOG_LEVEL: INFO
  CONFIG_SERVICE_URL: http://pronunt-config-service:8000
  AI_SERVICE_URL: http://pronunt-ai-service:8000

